
def printing():
    f=open('D:/ASAP FUNCTIONS/tempf.txt','w')
        f.write('     ASAP Super Store     \n')
        f.write('   Anamnager Kathmandu     \n')
        f.write('Bill no:')
        f.write(str(billno))
        f.write('\ncustomer name:')
        f.write(str(custName.get()))
        f.write('\ncustomer no:')
        f.write(str(custNumber.get()))
        f.write('\npayment mode: cash    \n')
        f.write('*******************************\n')
        f.write('sn   Items   rate qty Amount\n')
        f.write('******************************\n')
        for i in allval(prod_tree): 
            f.write(str(i).replace('(','').replace(')','').replace("'","").replace(',','  '))
            f.write('\n')
        f.write('******************************\n')
        f.write('               total:')
        f.write(str(total()))
        f.write('\n******************************\n')
        f.write('thank you for shopping in ASAP \n super store!!\n')
        f.write('!!See you Again!!')
        f.close()
        os.startfile('D:/ASAP FUNCTIONS/tempf.txt','print')